name: Interview Question
title: "[WIP] "
description: 면접 질문 목록(list) 등록합니다.
labels: ["Difficulty/Easy", "Role/Backend", "Subject/Javascript", "Type/Langauge"]
body:
  - type: textarea
    id: what-to-develop
    attributes:
      label: 1. Question
      value: 
        질문 내용: 
        - 
    validations:
      required: true
  - type: textarea
    id: develop-plan
    attributes:
      label: 2. My Answer
    validations:
      required: true
      
  - type: textarea
    id: what-to-develop
    attributes:
      label: 3. Question
      value: 
        질문 내용: 
        - 
    validations:
      required: true
  - type: textarea
    id: develop-plan
    attributes:
      label: 4. My Answer
    validations:
      required: true
      
      
  - type: textarea
    id: what-to-develop
    attributes:
      label: 5. Question
      value: 
        질문 내용: 
        - 
    validations:
      required: true
  - type: textarea
    id: develop-plan
    attributes:
      label: 6. My Answer
    validations:
      required: true
      
      
   - type: textarea
    id: what-to-develop
    attributes:
      label: 7. Question
      value: 
        질문 내용: 
        - 
    validations:
      required: true
  - type: textarea
    id: develop-plan
    attributes:
      label: 8. My Answer
    validations:
      required: true
      
      
  - type: textarea
    id: what-to-develop
    attributes:
      label: 9. Question
      value: 
        질문 내용: 
        - 
    validations:
      required: true
  - type: textarea
    id: develop-plan
    attributes:
      label: 10. My Answer
    validations:
      required: true
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
